<template>
  <div class="relative py-24 sm:py-32 bg-brand-dark">
    <!-- Gradient background effect -->
    <div class="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-brand-primary/20 via-brand-dark to-brand-dark"></div>

    <div class="mx-auto max-w-4xl px-6 lg:px-8">
      <div class="mx-auto max-w-2xl lg:max-w-none text-gray-300 space-y-8">
        <h1 class="text-4xl font-bold tracking-tight text-white sm:text-5xl mb-12">Privacy Policy</h1>
        
        <div class="space-y-6">
          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">1. Title</h2>
          <p><strong>App Name:</strong> SportsMania<br>
          <strong>Company Name:</strong> Location Tech<br>
          <strong>Effective Date:</strong> July 21, 2026</p>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">2. Introduction</h2>
          <p>Welcome to <strong>SportsMania</strong>, developed by Location Tech. SportsMania is a dual-role platform connecting athletes (Players) with sports venue owners (Venue Owners) to discover, book, and manage sports facilities.</p>
          <p>We are deeply committed to protecting your privacy and ensuring your data is handled securely. This Privacy Policy explains how we collect, use, and share your information when you use our services. By downloading, accessing, or using the SportsMania app, you signify that you have read, understood, and agree to the collection and use of your information as described in this policy.</p>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">3. Definitions</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable living individual (e.g., name, phone number, email).</li>
            <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).</li>
            <li><strong>Location Data:</strong> Information regarding the physical location of your device or the venues listed on our platform.</li>
            <li><strong>Service:</strong> The SportsMania mobile application and related backend infrastructure.</li>
            <li><strong>User:</strong> The individual accessing or using the Service, acting as either a Player or a Venue Owner.</li>
            <li><strong>Account:</strong> A unique account created for you to access our Service.</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">4. Information You Collect</h2>
          
          <h3 class="text-xl font-medium text-gray-100 mt-6 mb-2">Personal Information:</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>Phone Number (used as your primary identifier)</li>
            <li>Full Name (optional/profile info)</li>
            <li>Email Address (optional)</li>
            <li>Password (securely hashed, never stored in plain text)</li>
            <li>Profile Picture</li>
            <li>OTP Verification codes</li>
          </ul>

          <h3 class="text-xl font-medium text-gray-100 mt-6 mb-2">Device Information:</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>Device model and manufacturer</li>
            <li>Operating System (iOS or Android)</li>
            <li>App version</li>
            <li>Push notification tokens (via Expo)</li>
          </ul>

          <h3 class="text-xl font-medium text-gray-100 mt-6 mb-2">Usage Information:</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>Login times and session duration</li>
            <li>Features used (e.g., searches, feed scrolling)</li>
            <li>Booking history (pitch selections, match times, cancellations)</li>
          </ul>

          <h3 class="text-xl font-medium text-gray-100 mt-6 mb-2">Location Information:</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>City/Location of venues (provided by Venue Owners)</li>
            <li>Approximate or precise device location (to show nearby sports venues)</li>
          </ul>

          <h3 class="text-xl font-medium text-gray-100 mt-6 mb-2">Payment Information:</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>Transaction IDs, booking costs, and refund statuses</li>
            <li>Subscription status (for Venue Owners)</li>
            <li><em>Note: We do not store complete credit card or banking details. These are handled securely by our integrated payment providers.</em></li>
          </ul>

          <h3 class="text-xl font-medium text-gray-100 mt-6 mb-2">Uploaded Content:</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>Images (Venue Owners uploading high-resolution photos of their facilities)</li>
          </ul>

          <h3 class="text-xl font-medium text-gray-100 mt-6 mb-2">Local Storage:</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>Secure Tokens (JWT Authentication tokens stored securely via <code>expo-secure-store</code>)</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">5. Why You Collect Information</h2>
          <p class="mb-4">We collect your information for the following purposes:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Account Creation & Authentication:</strong> To register users, send OTPs via SMS, and secure your session.</li>
            <li><strong>Booking Management:</strong> To facilitate pitch reservations, manage operational hours, and process scheduling.</li>
            <li><strong>Payments & Payouts:</strong> To securely process booking fees, owner commissions, and potential refunds.</li>
            <li><strong>Customer Support:</strong> To assist you with account issues, booking conflicts, or technical problems.</li>
            <li><strong>Notifications:</strong> To send important booking reminders, manual review alerts, and system updates.</li>
            <li><strong>Analytics & Service Improvement:</strong> To understand how users interact with our UI, optimize our dynamic pricing rules, and improve app stability.</li>
            <li><strong>Security & Fraud Prevention:</strong> To protect against unauthorized access and ensure platform integrity.</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">6. Legal Basis</h2>
          <p class="mb-4">For users in jurisdictions where legal basis definitions apply, we process your data based on:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Contract Fulfillment:</strong> Processing is necessary to provide the Service you requested (e.g., booking a pitch).</li>
            <li><strong>User Consent:</strong> When you explicitly allow us access to your camera/photos or push notifications.</li>
            <li><strong>Legitimate Interests:</strong> For analytics, security monitoring, and service improvements.</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">7. Permissions Used</h2>
          <p class="mb-4">To provide our core features, the SportsMania app may request the following device permissions:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Camera & Photos (Storage):</strong> Required for Venue Owners to select and upload images of their venues to the gallery.</li>
            <li><strong>Notifications:</strong> Required to send push notifications for booking reminders and status updates.</li>
            <li><strong>Location:</strong> Used to dynamically fetch and display the nearest sports venues to your current area.</li>
            <li><strong>Network Access:</strong> Required for the app to communicate with our backend servers.</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">8. How Information is Shared</h2>
          <p class="mb-4">We share your information strictly to operate our platform. We share data with:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Payment Providers:</strong> To process transactions securely.</li>
            <li><strong>SMS Providers:</strong> To send OTP verification codes.</li>
            <li><strong>Cloud Hosting & Storage:</strong> To host our databases and store uploaded venue images securely.</li>
            <li><strong>Other Users:</strong> If you are a Player, the Venue Owner will see your booking details. If you are a Venue Owner, your venue details and location are visible to all Players.</li>
          </ul>
          <p class="italic mt-4">We do not sell your personal information to third parties.</p>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">9. Third-Party Services</h2>
          <p class="mb-4">We utilize the following external services to power SportsMania. Each service is governed by its own privacy policy:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Expo / EAS:</strong> For app framework, notifications, and over-the-air updates.</li>
            <li><strong>Twilio:</strong> For delivering SMS/OTP messages.</li>
            <li><strong>AWS (Amazon Web Services):</strong> Specifically AWS S3 for secure cloud storage of venue images.</li>
            <li><strong>PostgreSQL / Prisma:</strong> For our secure backend database management.</li>
            <li><strong>Payment Gateways (e.g., JazzCash, EasyPaisa, or Stripe):</strong> For processing financial transactions securely.</li>
            <li><strong>Mapbox / OpenStreetMap:</strong> For rendering maps and calculating spatial geodata for venues.</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">10. Data Retention</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Active Accounts:</strong> We retain your Personal Data, booking history, and venue information for as long as your account is active.</li>
            <li><strong>Deletion:</strong> Upon account deletion, your personal data is purged from our active databases.</li>
            <li><strong>Financial Records:</strong> Certain transaction data may be retained for longer periods to comply with legal, tax, or financial reporting obligations.</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">11. Data Security</h2>
          <p class="mb-4">We implement robust security measures to protect your data, including:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li>HTTPS/TLS encryption for all data transmitted between the app and our servers.</li>
            <li>Password hashing using bcrypt.</li>
            <li>Secure authentication using JSON Web Tokens (JWT) stored in your device's <code>expo-secure-store</code> keychain/keystore.</li>
            <li>Role-based access controls on our backend to protect owner and player data.</li>
          </ul>
          <p class="italic mt-4">However, please be aware that no electronic transmission or storage system can guarantee 100% absolute security.</p>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">12. International Data Transfers</h2>
          <p>Your information may be transferred to — and maintained on — servers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. By using the Service, you consent to these transfers.</p>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">13. User Rights</h2>
          <p class="mb-4">Depending on your region, you have the right to:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li>Access the Personal Data we hold about you.</li>
            <li>Update or correct your profile information via the app.</li>
            <li>Delete your account and associated data entirely.</li>
            <li>Withdraw consent for device permissions (like Notifications or Camera) at any time via your device settings.</li>
            <li>Contact our support team for any data-related inquiries.</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">14. Children's Privacy</h2>
          <p>SportsMania is not intended for use by children under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that we have collected Personal Data from a child without parental consent, we will take steps to remove that information from our servers.</p>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">15. Marketing Communications</h2>
          <p class="mb-4">We may occasionally send you promotional notifications regarding new venues, platform features, or discounts.</p>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Opt-Out:</strong> You can opt out of push notification marketing by adjusting your device notification settings.</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">16. Cookies & Tracking Technologies</h2>
          <p class="mb-4">Within the mobile app environment, we use:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Session Tokens:</strong> JWTs to maintain your logged-in state without requiring continuous re-authentication.</li>
            <li><strong>Cached Data:</strong> Local caching for images (via <code>expo-image</code>) to reduce data usage and improve load times.</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">17. Account Deletion</h2>
          <p class="mb-4">You have the right to delete your account at any time.</p>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>How to Delete:</strong> Navigate to your Profile settings within the app and select "Delete Account."</li>
            <li><strong>What is Deleted:</strong> Your profile details, hashed passwords, and unassociated user data are permanently deleted.</li>
            <li><strong>What is Retained:</strong> Booking records and transaction IDs may be retained in an anonymized or legally required format for financial compliance.</li>
          </ul>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">18. Changes to This Privacy Policy</h2>
          <p>We may update this Privacy Policy from time to time to reflect changes in our practices or for legal reasons. When we make updates, we will revise the "Effective Date" at the top of this policy. We encourage you to review this page periodically.</p>

          <hr class="border-gray-800 my-8">

          <h2 class="text-2xl font-semibold text-white mt-12 mb-4">19. Contact Information</h2>
          <p class="mb-4">If you have any questions or concerns about this Privacy Policy, please contact us:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Company Name:</strong> Location Tech</li>
            <li><strong>Contact Page:</strong> <a href="https://www.locationtechnologies.io/contact" class="text-brand-primary hover:text-white transition-colors">www.locationtechnologies.io/contact</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
useSeoMeta({
  title: 'SportsMania Privacy Policy — Location Tech',
  description: 'Privacy Policy for the SportsMania app developed by Location Tech.',
})
</script>
